# -------------------------------------------------------------------------------------
# Author Configuration
# -------------------------------------------------------------------------------------

name = "Karl"
email = "karl@stonkmarket.de"
link = "https://github.com/StasonJatham"
avatar = "/karl_square_yellow_back.jpeg"
about_me = "Hallo! Ich bin Karl. Ich investiere seit ich 18 bin und möchte von jetzt an mein investemnt Tagebuch öffentlich führen. Ich schreibe hier darüber warum ich Aktien kaufe und verkaufe. Das ganze ist nicht als Empfehlung zu verstehen, es ist nur mein persönliches Investment Tagebuch. Ansonsten mag ich gaming🎮, bouldern🪨, wandern🥾 und pizza🍕."
