# -------------------------------------------------------------------------------------
# Author Configuration
# -------------------------------------------------------------------------------------

email = "karl@karlcloud.de"
link = "https://github.com/StasonJatham"
avatar = "/smile_cat.png"
about_me = "katze"
name = "Karl"
