# -------------------------------------------------------------------------------------
# Author Configuration
# -------------------------------------------------------------------------------------

name = "Karl"
email = "karl@stonkmarket.de"
link = "https://github.com/StasonJatham"
avatar = "/karl_square_yellow_back.jpeg"
about_me = "Ich bin Karl und teile mein persönliches Investment-Tagebuch, um anderen zu helfen, ihr Wissen über das Investieren zu erweitern. Neben meinen finanziellen Interessen genieße ich Gaming🎮, Bouldern🪨, Wandern🥾 und Pizza🍕. Ich bin aufgeschlossen und immer bereit, neue Dinge auszuprobieren."
