# -------------------------------------------------------------------------------------
# Hugo Configuration
# See: https://gohugo.io/getting-started/configuration/
# -------------------------------------------------------------------------------------

title = "Koole Katzen"
baseURL = "https://katzen.karlcloud.de"
theme = "FixIt"
defaultContentLanguage = "de"
languageCode = "de"
hasCJKLanguage = true
enableRobotsTXT = true
enableEmoji = true
enableGitInfo = false
relativeURLs = false
buildDrafts = false
summaryLength = 150
# ignore some build errors
ignoreErrors = [
    "error-remote-getjson",
    "error-missing-instagram-accesstoken",
    "error-output-taxonomy",
]
